// Planet Photo — Viewfinder math (exposure triangle, focal length FoV), develop pipeline, catalog store.
// Generated by the Counted Repo Factory (seeds/seeds.yaml). Deterministic by construction.

import { seededRandom } from "./rng";
import { ExposureMath, DevelopPipeline, PhotoCatalog } from "./modules";

export const SPEC = "Viewfinder math (exposure triangle, focal length FoV), develop pipeline, catalog store.";
export const MODULES = [{ id: "ExposureMath", name: "Planet Photo :: ExposureMath" }, { id: "DevelopPipeline", name: "Planet Photo :: DevelopPipeline" }, { id: "PhotoCatalog", name: "Planet Photo :: PhotoCatalog" }];
export { seededRandom };
export class Registry {
  private items = new Map<string, string>();
  constructor(seed = 42) {
    const rng = seededRandom(seed);
    for (const mod of MODULES) {
      const n = 1 + Math.floor(rng() * 4);
      for (let i = 0; i < n; i++) {
        this.items.set(mod.id + "-" + i, mod.name);
      }
    }
  }
  count(): number { return this.items.size; }
  get(id: string): string | undefined { return this.items.get(id); }
  ids(): string[] { return [...this.items.keys()]; }
  lookup(name: string): string[] {
    return this.ids().filter((id) => this.items.get(id) === name);
  }
}
